name: Pull Request Checks
on:
  push:
    branches-ignore:
      - main

jobs:
  verify:
    name: Verify Code
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v2

      - name: Install Java 20
        uses: actions/setup-java@v2
        with:
          distribution: 'temurin'
          java-version: '20'
          cache: 'gradle'

      - name: Build with Gradle
        run: ./gradlew build